#!/bin/bash
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ]; then
    echo "----------------------------------------------------------"
    echo "❌ STOP: No commits on main branch allowed"
    echo "Create a feature branch and use a pull request on Github."
    echo "----------------------------------------------------------"
    exit 1
fi
